"""empty message

Revision ID: 681867cbedb7
Revises: 
Create Date: 2020-11-06 16:16:38.934174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681867cbedb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
