# build environment

FROM node:14.15 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

# set args REACT_APP_USERS_SERVICE_URL and NODE_ENV
# ARG REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
# ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL

COPY package.json /usr/src/app/package.json
RUN npm install --silent
RUN npm install create-react-app@4.0.0 --global

COPY . /usr/src/app

RUN npm run build


# production environment
FROM nginx:1.19.2-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]